---
all:
  hosts:
    sonar-01:
      ansible_host: 89.169.147.227
    nexus-01:
      ansible_host: 89.169.155.177
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: kkm
